# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Io.js and Node.js.
environment:
  matrix:
  # node.js
    - nodejs_version: "0.8"
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
  # io.js
    - nodejs_version: "1"
    - nodejs_version: "2"
    - nodejs_version: "3"

# Install scripts. (runs after repo cloning)
install:
  # Typical npm stuff.
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm test

# Don't actually build.
build: off